format = """
[](#3B4252)\
$username\
[](bg:#434C5E fg:#3B4252)\
$directory\
[](fg:#434C5E bg:#4C566A)\
$git_branch\
$git_status\
[](fg:#4C566A bg:#86BBD8)\
$all\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
$aws\
[](fg:#06969A bg:#33658A)\
$time\
$cmd_duration\
[](fg:#33658A)\
$line_break\
$character\
"""

command_timeout = 5000

[character] # The name of the module we are configuring is 'character'
success_symbol = '[❯](bold green)'
error_symbol = '[✗](bold red)'
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#3B4252"
style_root = "bg:#3B4252"
format = '[$user ]($style)'

[directory]
style = "bg:#434C5E"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = " "

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = ""
"Downloads" = ""
"Music" = ""
"Pictures" = ""
"Important " = ""
"development" = "󰵮"

[docker_context]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[aws]
symbol = ""
format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
style = "bg:#06969A"

[git_branch]
symbol = ""
style = "bg:#4C566A"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#4C566A"
format = '[$all_status$ahead_behind ]($style)'

[nix_shell]
format = '[ $symbol $state ]($style)'
style = "fg:#4C566A bg:#86BBD8"
symbol = "󱄅"
impure_msg = "*"

[c]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) (\($virtualenv\)) ]($style)'

[golang]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ $time ]($style)'


[cmd_duration]
disabled = false
style = "bg:#33658A"
format = '[ $duration ]($style)'
